# Generated by Django 5.0.6 on 2024-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Adresse')),
                ('age', models.CharField(max_length=16, verbose_name='Telephone')),
            ],
        ),
    ]
