# Generated by Django 5.0.6 on 2024-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0002_personne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='age',
            field=models.CharField(max_length=16, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='name',
            field=models.CharField(max_length=20, verbose_name='name'),
        ),
    ]
