# Generated by Django 5.0.6 on 2024-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rv', '0004_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rv',
            name='patient',
        ),
        migrations.AddField(
            model_name='rv',
            name='patient',
            field=models.ManyToManyField(blank=True, null=True, related_name='Patient', to='rv.patient'),
        ),
    ]
